### ISSUE TITLE
Reporte de Practica (TextBox)

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Brisa-4#2]
[Reporte de Práctica(TextBox).pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Brisa-4/files/6346157/Reporte.de.Practica.TextBox.pdf)

**Comment by KarlaV0** [comment]
Calificación: 20%
Calificó: Karla Vásquez Ortiz

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
